### ISSUE TITLE
Failed to flash WIFIDS10WT

### ISSUE THREAD

**Issue by MrMEEE** [ct-Open-Source/tuya-convert#1064]
### Before opening a new issue, please read the following

Trying to flash my Nedis WIFIDS10MT Smoke detector:

IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Auto retry in 1s. ..............................................................................
Timed out while waiting for the device to (re)connect
======================================================
Attempting to diagnose the issue...
An ESP82xx based device connected according to your wifi log.
If this is the device you are trying to flash, another issue may be preventing it from flashing.
Otherwise, it could be that the device does not use an ESP82xx or it did not connect.
For additional information, check the *.log files inside the scripts folder.
Please include these logs when opening a new issue on our GitHub issue tracker.
======================================================
Do you want to try flashing another device? [y/N] N
======================================================
Cleaning up...
Closing AP
Exiting...

Can anyone help me out?

**Comment by MrMEEE** [comment]
==> smarthack-mqtt.log <==
1662846375: mosquitto version 2.0.11 running
^C1662846470: mosquitto version 2.0.11 terminating
1662846584: mosquitto version 2.0.11 starting
1662846584: Using default config.
1662846584: Starting in local only mode. Connections will only be possible from clients running on this machine.
1662846584: Create a configuration file which defines a listener to allow remote access.
1662846584: For more details see https://mosquitto.org/documentation/authentication-methods/
1662846584: Opening ipv4 listen socket on port 1883.
1662846584: Opening ipv6 listen socket on port 1883.
1662846584: mosquitto version 2.0.11 running

==> smarthack-psk.log <==
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41223
could not establish sslpsk socket: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41225
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41227
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!

==> smarthack-udp.log <==
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^C/home/mj/Hentet/tuya-convert/scripts/./tuya-discovery.py:50: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^C/home/mj/Hentet/tuya-convert/scripts/./tuya-discovery.py:50: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667

==> smarthack-web.log <==
^CReceived SIGINT, exiting...
Listening on 10.42.42.1:80
[I 220910 23:49:52 web:2271] 302 GET /generate_204 (10.42.42.28) 0.56ms
[I 220910 23:49:52 web:2271] 302 GET /generate_204 (10.42.42.28) 0.70ms
[I 220910 23:49:52 web:2271] 200 GET / (10.42.42.28) 1.04ms
[I 220910 23:49:52 web:2271] 302 GET /favicon.ico (10.42.42.28) 0.67ms
[I 220910 23:49:53 web:2271] 304 GET / (10.42.42.28) 0.70ms
[I 220910 23:49:54 web:2271] 302 GET /generate_204 (10.42.42.28) 0.54ms
[I 220910 23:49:54 web:2271] 302 GET /generate_204 (10.42.42.28) 0.57ms
[I 220910 23:50:12 web:2271] 302 GET /generate_204 (10.42.42.28) 0.66ms

==> smarthack-wifi.log <==
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlp3s0...
wlp3s0: interface state UNINITIALIZED->ENABLED
wlp3s0: AP-ENABLED 
wlp3s0: AP-STA-CONNECTED 5c:77:76:97:0a:10
wlp3s0: AP-STA-CONNECTED f4:cf:a2:5c:e2:fb

==> smarthack-web.log <==

GET /gw.json?a=s.gw.token.get&et=1&gwId=04876840f4cfa25ce2fb&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":28,"source":"ap","path":"multicast"}}&t=4&v=3.0&sign=965ffaf3317182d0b9c8391f88395db7
Host: a3.tuyaus.com
User-Agent: ESP8266SDK
Connection: keep-alive

Answer s.gw.token.get
reply {"t":1662846629,"e":false,"success":true,"result":{"gwApiUrl":"http://10.42.42.1/gw.json","stdTimeZone":"-05:00","mqttRanges":"","timeZone":"-05:00","httpsPSKUrl":"https://10.42.42.1/gw.json","mediaMqttUrl":"10.42.42.1","gwMqttUrl":"10.42.42.1","dstIntervals":[],"mqttsUrl":"10.42.42.1","mqttsPSKUrl":"10.42.42.1","mediaMqttsUrl":"10.42.42.1","aispeech":"10.42.42.1"}}
[I 220910 23:50:29 web:2271] 200 GET /gw.json?a=s.gw.token.get&et=1&gwId=04876840f4cfa25ce2fb&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":28,"source":"ap","path":"multicast"}}&t=4&v=3.0&sign=965ffaf3317182d0b9c8391f88395db7 (10.42.42.1) 25.56ms

POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=04876840f4cfa25ce2fb&other={"token":"00000000"}&t=4&v=3.0&sign=6935eb688ebaf464abf58f12b5f15faa
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 549

payload F5F5B292214DB84D365D6FF20FB9CEAAC37F83F01E795028F216B078F434E7DB53CA4E200D8344D01820418A14C367AE97B66C3FBD3B9D8B2BC62ED82AD0D96874EF216AE907577E04A925B0203771A35E75CBAEAEBE8EEE96726EF35882F578F04B1FA2EDB5FDD9F9B0FA933DEFEEFDFF2737FBF7AE6DCE36BBEB1BD8B367F36D0EE49CE20410EE6A2CED1D7C2176F5BEB9885C7C0EF39A0AB606D062A6A9B0094B8657BE91E22F93E0B5E71B2DC166B525448616D4967D3F09379C2A850B367FAC8F5F7A4C6876A40A53E0629BEEF27DDDB0A05624215058B38A6820F7B05C74068570EE80F6406051899C2752D8AA5DF2564B564E54E7510549B7B3D84E9B4F52BDD4E3198FEEC76222E737F4DC50
Answer s.gw.dev.pk.active
reply {"t":1662846630,"e":false,"success":true,"result":{"schema":"[{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"}]","uid":"00000000000000000000","devEtag":"0000000000","secKey":"0000000000000000","schemaId":"0000000000","localKey":"0000000000000000"}}
TRIGGER UPGRADE IN 10 SECONDS
[I 220910 23:50:30 web:2271] 200 POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=04876840f4cfa25ce2fb&other={"token":"00000000"}&t=4&v=3.0&sign=6935eb688ebaf464abf58f12b5f15faa (10.42.42.1) 16.35ms

POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=04876840f4cfa25ce2fb&t=5&v=1.0&sign=0ba701c933bd8e1eb031f03f60cef295
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-
urlencoded; charset=UTF-8
Content-Length: 0

Answer tuya.device.dynamic.config.get
reply {"result":"fn8oBaEAaJe3I+enO7OkYdd0LkD9WHnY6k8vmvctrJZY0YFldNM2URMMaGS92UKj9F2VBmqNqTqJcWuiX4YubMavCcK/KUhV7OC22FxXOoS7mevrGF2WUpAllBDW/Q5l","t":1662846630,"sign":"9fb4a6cc6f8b5bbc"}
[I 220910 23:50:30 web:2271] 200 POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=04876840f4cfa25ce2fb&t=5&v=1.0&sign=0ba701c933bd8e1eb031f03f60cef295 (10.42.42.1) 1.21ms

==> smarthack-psk.log <==
new client on port 443 from 10.42.42.28:41233
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.18:23244
ID: 0142416f3f3f3f3f3f3f3f3f3f3f3f3f3f30677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
Prefix: b'BAo?????????????'
PSK: f0e62c3d1e0d963e37060fa9f4421c4016cd890dbdbc0b0ca76711d3b0404ae3
new client on port 443 from 10.42.42.18:24123
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
new client on port 8886 from 10.42.42.18:32618
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 443 from 10.42.42.18:31155
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
new client on port 8886 from 10.42.42.18:29635
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 443 from 10.42.42.28:41235
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.18:19342
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:26952
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused

==> smarthack-web.log <==
encoding {"data":{"gwId":"04876840f4cfa25ce2fb"},"protocol":15,"s":"1523715","t":"1662846640"} using protocol 2.2
b'2.2\xac\xeau@84664045\xb7\x98\xa7\x08\xc0\xc7\xa5\xc2JB\x9c_9\xed\x91m\x95.\xd50H\xdf\xa3\x0e\x16\x99Q\xf30\r\x0cl\xee4\x85\x87h\xf2\xce\x1f5~GjP\xde\xa0\xe6\x91\xfa\xef\xd4\xa8\xffL\x1a\xef\x01\r\x8e\xbd\xf5EL\xb8=#\xffO~\x02\xc9\xd78\x17U\xae:r*\xe1XD\xabf\xd6$U\x86\xe7t\x0cF\x9a\x0e\xb5'

==> smarthack-psk.log <==
new client on port 443 from 10.42.42.28:41237
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.18:58216
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:24611
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:4787
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:21573
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:12455
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:18892
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:59196
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 443 from 10.42.42.28:41241
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.18:28088
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:21335
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused

==> smarthack-mqtt.log <==
1662846640: New connection from 127.0.0.1:43917 on port 1883.
1662846640: New client connected from 127.0.0.1:43917 as auto-D60C6BF3-8D93-8732-84CA-0243A9C76D13 (p2, c1, k60).
1662846640: No will message specified.
1662846640: Sending CONNACK to auto-D60C6BF3-8D93-8732-84CA-0243A9C76D13 (0, 0)
1662846640: Received PUBLISH from auto-D60C6BF3-8D93-8732-84CA-0243A9C76D13 (d0, q0, r0, m0, 'smart/device/in/04876840f4cfa25ce2fb', ... (111 bytes))
1662846640: Received DISCONNECT from auto-D60C6BF3-8D93-8732-84CA-0243A9C76D13
1662846640: Client auto-D60C6BF3-8D93-8732-84CA-0243A9C76D13 disconnected.

==> smarthack-psk.log <==
new client on port 8886 from 10.42.42.18:23734
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:23705
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:21076
ID: 0142416f68626d6436613f3f3f3f3f3f3f30677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
Prefix: b'BAohbmd6a???????'
PSK: 14c4092b975e33a2a2ed70f5dddc5029ccc9ffb0017cda6e1097c606e2a8bf56
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:40829
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:18149
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 443 from 10.42.42.28:41251
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.18:16926
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:15452
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:56363
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 443 from 10.42.42.28:41253
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.18:23293
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:49102
ID: 0142416f68626d643661473f3f3f3f3f3f30677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
Prefix: b'BAohbmd6aG??????'
PSK: 24e461ff93a996f546427489c3e07f2f588f9ed9ef2887a55b4d175014660e93
[Errno 111] Connection refused
new client on port 443 from 10.42.42.28:41255
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.18:20117
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:35947
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:27430
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:11431
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:24739
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:40823
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:22398
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 8886 from 10.42.42.18:20012
ID: 0142416f68626d6436614739314946523130677e391dfd698222f8ced072d06dcd5f5dc9c31fc3fe437b48a53abb38cfcf7c
PSK: b8eaa1894ec707f4e431de7fe46548b6b9048ba08a9ffe5a33594a4190a64835
[Errno 111] Connection refused
new client on port 443 from 10.42.42.28:41259
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41261
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41263
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41265
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41267
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41271
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41273
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41279
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.28:41281
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:997)
don't panic this is probably just your phone!
^CTraceback (most recent call last):
  File "/home/mj/Hentet/tuya-convert/scripts/./psk-frontend.py", line 113, in <module>
    main()
  File "/home/mj/Hentet/tuya-convert/scripts/./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt

==> smarthack-web.log <==
^CReceived SIGINT, exiting...

==> smarthack-mqtt.log <==
^C1662846721: mosquitto version 2.0.11 terminating

==> smarthack-udp.log <==
^C
==> smarthack-wifi.log <==
wlp3s0: interface state ENABLED->DISABLED
wlp3s0: AP-STA-DISCONNECTED f4:cf:a2:5c:e2:fb
wlp3s0: AP-STA-DISCONNECTED 5c:77:76:97:0a:10
wlp3s0: AP-DISABLED 
wlp3s0: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlp3s0 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...

**Comment by kueblc** [comment]
Thanks for your detailed logs @MrMEEE 

It looks like this device should be supported, however it is not accepting the fake config.get API response.

I've seen this come up before and at the moment, I do not know of a workaround. I can take another look soon and let you know if I find anything you can try.

**Comment by west89** [comment]
> Thanks for your detailed logs @MrMEEE
> 
> It looks like this device should be supported, however it is not accepting the fake config.get API response.
> 
> I've seen this come up before and at the moment, I do not know of a workaround. I can take another look soon and let you know if I find anything you can try.

The endless loop also occurs with the Nous A1 product, which is identical in construction to the Gosund SP111 and the BlitzWolf SHP6: 

SmartConfig complete.
Resending SmartConfig Packets

**Comment by olliemaller** [comment]
i have the same issue. Does anyone have a fix
