### ISSUE TITLE
Cant flash Tuya TC-US 

### ISSUE THREAD

**Issue by haianhlc99** [ct-Open-Source/tuya-convert#217]
Hello I'm flashing Tuya TC-US 2 gang and it stopped here
here is my logs

smarthack-mqtt

> 1560774309: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1560774309: Using default config.
1560774309: Opening ipv4 listen socket on port 1883.
1560774309: Opening ipv6 listen socket on port 1883.
^C1560775106: mosquitto version 1.4.10 terminating
1560775116: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1560775116: Using default config.
1560775116: Opening ipv4 listen socket on port 1883.
1560775116: Opening ipv6 listen socket on port 1883.
^C1560775316: mosquitto version 1.4.10 terminating
1560775321: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1560775321: Using default config.
1560775321: Opening ipv4 listen socket on port 1883.
1560775321: Opening ipv6 listen socket on port 1883.
^C1560776097: mosquitto version 1.4.10 terminating
1560776102: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1560776102: Using default config.
1560776102: Opening ipv4 listen socket on port 1883.
1560776102: Opening ipv6 listen socket on port 1883.
^C1560776607: mosquitto version 1.4.10 terminating
1560776611: mosquitto version 1.4.10 (build date Wed, 13 Feb 2019 00:45:38 +0000) starting
1560776611: Using default config.
1560776611: Opening ipv4 listen socket on port 1883.
1560776611: Opening ipv6 listen socket on port 1883.

smarthack-smartconfig

> Put` Device in Learn Mode! Sending SmartConfig Packets now
Sending SSID                  vtrust-flash
Sending wifiPassword          flashmeifyoucan
SmartConfig in progress
..........
SmartConfig complete.
Put Device in Learn Mode! Sending SmartConfig Packets now
Sending SSID                  vtrust-flash
Sending wifiPassword          flashmeifyoucan
SmartConfig in progress
..........
SmartConfig complete.
Put Device in Learn Mode! Sending SmartConfig Packets now
Sending SSID                  vtrust-flash
Sending wifiPassword          flashmeifyoucan
SmartConfig in progress
..........
SmartConfig complete.
Put Device in Learn Mode! Sending SmartConfig Packets now
Sending SSID                  vtrust-flash
Sending wifiPassword          flashmeifyoucan
SmartConfig in progress
..........
SmartConfig complete.
Put Device in Learn Mode! Sending SmartConfig Packets now
Sending SSID                  vtrust-flash
Sending wifiPassword          flashmeifyoucan
SmartConfig in progress
..........
SmartConfig complete.

smarthack-web

> Traceback` (most recent call last):
File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
ImportError: No module named 'tornado'
Traceback (most recent call last):
  File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
ImportError: No module named 'tornado'
Traceback (most recent call last):
  File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
ImportError: No module named 'tornado'
Traceback (most recent call last):
  File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
ImportError: No module named 'tornado'
Traceback (most recent call last):
  File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
ImportError: No module named 'tornado'

smarthack-wifi

> Backing up NetworkManager.cfg...
Restarting NetworkManager...
Backing up /etc/dnsmasq.conf...
Writing dnsmasq config file...
Creating new /etc/dnsmasq.conf...
Writing hostapd config file...
Configuring AP interface...
Applying iptables rules...
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Starting DNSMASQ server...
Starting AP on wlan0 in screen terminal...
Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:da:ef:de and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session 7F3045D3FE0F6A98
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: associated
wlan0: AP-STA-CONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d RADIUS: starting accounting session 8D6AD5D75645954A
wlan0: STA bc:dd:c2:28:ea:6d WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d WPA: group key handshake completed (RSN)
wlan0: STA 40:9c:28:a9:8f:92 WPA: group key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
^Cwlan0: interface state ENABLED->DISABLED
wlan0: AP-STA-DISCONNECTED 40:9c:28:a9:8f:92
wlan0: AP-DISABLED 
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Backing up NetworkManager.cfg...
Restarting NetworkManager...
Backing up /etc/dnsmasq.conf...
Writing dnsmasq config file...
Creating new /etc/dnsmasq.conf...
Writing hostapd config file...
Configuring AP interface...
Applying iptables rules...
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Starting DNSMASQ server...
RTNETLINK answers: File exists
Starting AP on wlan0 in screen terminal...
Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:da:ef:de and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session 7C66215AFD4A65DF
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session A0E21539A5DD3C57
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: associated
wlan0: AP-STA-CONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d RADIUS: starting accounting session 5A68F75F2A5BBD9B
wlan0: STA bc:dd:c2:28:ea:6d WPA: pairwise key handshake completed (RSN)
^Cwlan0: interface state ENABLED->DISABLED
wlan0: AP-STA-DISCONNECTED bc:dd:c2:28:ea:6d
wlan0: AP-STA-DISCONNECTED 40:9c:28:a9:8f:92
wlan0: AP-DISABLED 
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Backing up NetworkManager.cfg...
Restarting NetworkManager...
Backing up /etc/dnsmasq.conf...
Writing dnsmasq config file...
Creating new /etc/dnsmasq.conf...
Writing hostapd config file...
Configuring AP interface...
Applying iptables rules...
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Starting DNSMASQ server...
RTNETLINK answers: File exists
Starting AP on wlan0 in screen terminal...
Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:da:ef:de and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session 0D6835E054E744CF
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: associated
wlan0: AP-STA-CONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d RADIUS: starting accounting session 698622E00E654D44
wlan0: STA bc:dd:c2:28:ea:6d WPA: pairwise key handshake completed (RSN)
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session 20684D2C31F1C2F8
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: associated
wlan0: AP-STA-CONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d RADIUS: starting accounting session CF7E2774E50D6398
wlan0: STA bc:dd:c2:28:ea:6d WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 WPA: group key handshake completed (RSN)
^Cwlan0: interface state ENABLED->DISABLED
wlan0: AP-STA-DISCONNECTED 40:9c:28:a9:8f:92
wlan0: AP-DISABLED 
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Backing up NetworkManager.cfg...
Restarting NetworkManager...
Backing up /etc/dnsmasq.conf...
Writing dnsmasq config file...
Creating new /etc/dnsmasq.conf...
Writing hostapd config file...
Configuring AP interface...
Applying iptables rules...
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Starting DNSMASQ server...
RTNETLINK answers: File exists
Starting AP on wlan0 in screen terminal...
Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:da:ef:de and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session B5EB64E76637D483
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session 85085268167645E1
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: associated
wlan0: AP-STA-CONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d RADIUS: starting accounting session F39A12B7854DCE22
wlan0: STA bc:dd:c2:28:ea:6d WPA: pairwise key handshake completed (RSN)
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED 40:9c:28:a9:8f:92
wlan0: STA 3c:dc:bc:f1:bc:03 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 3c:dc:bc:f1:bc:03
wlan0: STA 3c:dc:bc:f1:bc:03 RADIUS: starting accounting session BABFB03C73BAA0E8
wlan0: STA 3c:dc:bc:f1:bc:03 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
^Cwlan0: interface state ENABLED->DISABLED
wlan0: AP-STA-DISCONNECTED 3c:dc:bc:f1:bc:03
wlan0: AP-DISABLED 
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Backing up NetworkManager.cfg...
Restarting NetworkManager...
Backing up /etc/dnsmasq.conf...
Writing dnsmasq config file...
Creating new /etc/dnsmasq.conf...
Writing hostapd config file...
Configuring AP interface...
Applying iptables rules...
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Starting DNSMASQ server...
RTNETLINK answers: File exists
Starting AP on wlan0 in screen terminal...
Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:da:ef:de and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: STA 3c:dc:bc:f1:bc:03 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 3c:dc:bc:f1:bc:03
wlan0: STA 3c:dc:bc:f1:bc:03 RADIUS: starting accounting session 9574DF1991C2B2DA
wlan0: STA 3c:dc:bc:f1:bc:03 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: associated
wlan0: AP-STA-CONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d RADIUS: starting accounting session C52960B39CED9027
wlan0: STA bc:dd:c2:28:ea:6d WPA: pairwise key handshake completed (RSN)
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: AP-STA-POSSIBLE-PSK-MISMATCH 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: disassociated
wlan0: STA 40:9c:28:a9:8f:92 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 40:9c:28:a9:8f:92
wlan0: STA 40:9c:28:a9:8f:92 RADIUS: starting accounting session F4F0CB59B19601AD
wlan0: STA 40:9c:28:a9:8f:92 WPA: pairwise key handshake completed (RSN)
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: AP-STA-DISCONNECTED bc:dd:c2:28:ea:6d
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated
wlan0: STA bc:dd:c2:28:ea:6d IEEE 802.11: disassociated

**Comment by kueblc** [comment]
Make sure your system is up to date and you've installed all the prerequisites. Skimming through the logs I see you don't have `tornado` installed and you need to update `iptables`.

**Comment by kueblc** [comment]
Closing due to inactivity. If you're still having issues, try the latest `tuya-convert` and open a new issue.
