### ISSUE TITLE
Issue when running start_flash.sh on fresh Debian install "ImportError: No module named 'Crypto'"

### ISSUE THREAD

**Issue by JoshuaSG** [ct-Open-Source/tuya-convert#274]
I'm using an OrangePiZero+, and installed the latest Debian version of Armbian. Followed the install instructions and everything seems to work and I get to the point where you get repeated periods while waiting for the device to appear. 

Here is my smarthack-smartconfig.log
`Traceback (most recent call last):
  File "./smartconfig/main.py", line 15, in <module>
    from smartconfig import smartconfig
  File "/home/joshua/tuya-convert/scripts/smartconfig/smartconfig.py", line 43, in <module>
    from multicast import multicast_head, encode_multicast_body
  File "/home/joshua/tuya-convert/scripts/smartconfig/multicast.py", line 12, in <module>
    from Crypto.Cipher import AES
ImportError: No module named 'Crypto'`

**Comment by JoshuaSG** [comment]
Got it fixed by running the following two commands
`sudo apt-get install python3-dev`
'pip3 install pycrypto'
