### ISSUE TITLE
How to flash Gosund SP111

### ISSUE THREAD

**Issue by membersound** [ct-Open-Source/tuya-convert#747]
I'm unable to flash the SP111 device OTA.
The AP starts up, smartphone connects, sp111 is set into discovery mode (blue light blinks fast).

As soon as I start the flashing routine, the blinking stops, and the docker container only shows the following output. What could I do?

```

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..........
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] 

```

The logs don't seem too bad:

smarthack-mqtt.log:
```
1597839645: mosquitto version 1.4.15 (build date Tue, 18 Jun 2019 11:42:22 -0300) starting
1597839645: Using default config.
1597839645: Opening ipv4 listen socket on port 1883.
1597839645: Opening ipv6 listen socket on port 1883.
1597839667: New connection from 127.0.0.1 on port 1883.
1597839667: New client connected from 127.0.0.1 as 275c4b77-cd6e-454f-8b75-ae308cbff507 (c1, k60).
1597839667: Sending CONNACK to 275c4b77-cd6e-454f-8b75-ae308cbff507 (0, 0)
1597839667: Received PUBLISH from 275c4b77-cd6e-454f-8b75-ae308cbff507 (d0, q0, r0, m0, 'smart/device/in/08152440f4cfa201bf97', ... (111 bytes))
1597839667: Received DISCONNECT from 275c4b77-cd6e-454f-8b75-ae308cbff507
1597839667: Client 275c4b77-cd6e-454f-8b75-ae308cbff507 disconnected.
1597839750: New connection from 10.42.42.1 on port 1883.
1597839750: New client connected from 10.42.42.1 as 08152440f4cfa201bf97 (c1, k60, u'08152440f4cfa201bf97').
1597839750: Sending CONNACK to 08152440f4cfa201bf97 (0, 0)
1597839750: Received SUBSCRIBE from 08152440f4cfa201bf97
1597839750:     smart/device/in/08152440f4cfa201bf97 (QoS 0)
1597839750: 08152440f4cfa201bf97 0 smart/device/in/08152440f4cfa201bf97
1597839750: Sending SUBACK to 08152440f4cfa201bf97
1597839757: New connection from 127.0.0.1 on port 1883.
1597839757: New client connected from 127.0.0.1 as 61b05151-2683-4e13-8ae5-3f5a06432489 (c1, k60).
1597839757: Sending CONNACK to 61b05151-2683-4e13-8ae5-3f5a06432489 (0, 0)
1597839757: Received PUBLISH from 61b05151-2683-4e13-8ae5-3f5a06432489 (d0, q0, r0, m0, 'smart/device/in/08152440f4cfa201bf97', ... (111 bytes))
1597839757: Sending PUBLISH to 08152440f4cfa201bf97 (d0, q0, r0, m0, 'smart/device/in/08152440f4cfa201bf97', ... (111 bytes))
1597839757: Received DISCONNECT from 61b05151-2683-4e13-8ae5-3f5a06432489
1597839757: Client 61b05151-2683-4e13-8ae5-3f5a06432489 disconnected.
1597839765: Received PUBLISH from 08152440f4cfa201bf97 (d0, q0, r0, m0, 'smart/device/out/08152440f4cfa201bf97', ... (80 bytes))
1597839768: Received PUBLISH from 08152440f4cfa201bf97 (d0, q0, r0, m0, 'smart/device/out/08152440f4cfa201bf97', ... (81 bytes))
^C1597839780: mosquitto version 1.4.15 terminating
```

smarthack-psk.log:
```
new client on port 443 from 10.42.42.40:36113
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:5857
ID: 0142416f68626d643661473931493f3f3ff2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
Prefix: b'BAohbmd6aG91I???'
PSK: 847907ad602c08bcb583db69f47fcbf146b27ba6a04bca398654bbb3336ba23d
new client on port 443 from 10.42.42.38:51522
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.38:51524
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.38:51534
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.38:51536
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.38:51538
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.38:51540
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.40:8081
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:12639
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:42237
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 8886 from 10.42.42.40:10439
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:29735
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:49170
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:3558
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:29390
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
new client on port 443 from 10.42.42.40:20206
ID: 0142416f68626d64366147393149465231f2798befd09cc85c8a72ec05908c8f545fdb254796cbfd5c291e430f4262d6c3eb
PSK: 717d08f8669ee59903086f8853a7dc74c5d88255a843067faaae93538a9763a4
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt

```

smarthack-udp.log:
```
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
10.42.42.40 {"ip":"10.42.42.40","gwId":"08152440f4cfa201bf97","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"37mnhia3pojleqfh","version":"3.3"}
```
smarthack-web.log:
```
Listening on 10.42.42.1:80

GET /gw.json?a=s.gw.token.get&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":2,"source":"ap","path":"broadcast"}}&t=6&v=3.0&sign=24e0d1d29be990ad75e68c5d31724b91
Host: a3.tuyaus.com
User-Agent: ESP8266SDK
Connection: keep-alive

Answer s.gw.token.get
reply {"t":1597839656,"e":false,"success":true,"result":{"gwApiUrl":"http://10.42.42.1/gw.json","stdTimeZone":"-05:00","mqttRanges":"","timeZone":"-05:00","httpsPSKUrl":"https://10.42.42.1/gw.json","mediaMqttUrl":"10.42.42.1","gwMqttUrl":"10.42.42.1","dstIntervals":[],"mqttsUrl":"10.42.42.1","mqttsPSKUrl":"10.42.42.1","mediaMqttsUrl":"10.42.42.1","aispeech":"10.42.42.1"}}
[I 200819 12:20:56 web:2250] 200 GET /gw.json?a=s.gw.token.get&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":2,"source":"ap","path":"broadcast"}}&t=6&v=3.0&sign=24e0d1d29be990ad75e68c5d31724b91 (10.42.42.1) 22.83ms

POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000"}&t=7&v=3.0&sign=676397d1b0c1da1fdbabbb2b4531e9b3
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 485

payload 40DD6ADE8D7481782D5EC5EBBCBE4089CDA06990C12FBCFE39F6364ADF39D7ADAB683C9A21E5F5878B1E240BC933C1FFA829DCE8A955CD45A257FDCEAFE164A0E8427C9EEC654F2E8C162D37D70CEE7D8E0A5ADCEA9D9060B6C3E470488DE6B58859618360490C926AAA32E35B935BDE2AAF4AFB259F5CE7445821983872E8216D941EE7968B142B0A2B32D5A1B42B1C11BFB354572DA2974A00E8D9C2618CD0EFB73DE16C83F83B8EBE1F551986F42500FF45B75E9602209B666F648AE563D92843F85BAD1B7BC258B0D1220B32E6A0A3680BB8C52F762848355238E27BD08489DAD6B43E976E60EBAB08DD038EB317
Answer s.gw.dev.pk.active
reply {"t":1597839657,"e":false,"success":true,"result":{"schema":"[{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"}]","uid":"00000000000000000000","devEtag":"0000000000","secKey":"0000000000000000","schemaId":"0000000000","localKey":"0000000000000000"}}
TRIGGER UPGRADE IN 10 SECONDS
[I 200819 12:20:57 web:2250] 200 POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000"}&t=7&v=3.0&sign=676397d1b0c1da1fdbabbb2b4531e9b3 (10.42.42.1) 109.26ms
[I 200819 12:21:04 web:2250] 302 GET /generate_204_8b2afca1-47e2-4fce-bc2c-fb3d26ddbd20 (10.42.42.38) 2.53ms
[I 200819 12:21:05 web:2250] 302 GET /generate_204_da175f06-5d71-4ab3-9df8-0b5291b24ac8 (10.42.42.38) 1.96ms
[I 200819 12:21:05 web:2250] 302 GET /generate_204_8c5e28e5-e800-4d9e-8932-fcaafca733f0 (10.42.42.38) 1.86ms
[I 200819 12:21:07 web:2250] 302 GET /generate_204 (10.42.42.38) 2.16ms
encoding {"data":{"gwId":"08152440f4cfa201bf97"},"protocol":15,"s":"1523715","t":"1597839667"} using protocol 2.2
b'2.2\x87\\\x18\xad83966780\xb7\x98\xa7\x08\xc0\xc7\xa5\xc2JB\x9c_9\xed\x91m\xe7%\xf0E\xfa\x0b\xcc\x06\xd4kN_5#W\xb0\xfd\xe9y\xbb\x8a\xb0=\xc1\x89\x1b{\x8c\xe6\xb0?\x89\x91\xfa\xef\xd4\xa8\xffL\x1a\xef\x01\r\x8e\xbd\xf5EL\xab\x9a\xc2\xba0\xc5\xd7b\x84$L\xf4\xe3\xa08\xd6\x00\x15\xbf\xa8\xa4^/\xcb\xe3P>\x95\xc4\xcf\xdb\xb5'
[I 200819 12:21:08 web:2250] 302 GET /generate_204_6ca7dc02-3d55-4afc-9f0f-e80f8489932c (10.42.42.38) 1.71ms
[I 200819 12:21:38 web:2250] 302 GET /generate_204_78a19ace-bbc2-4fce-a01d-82e1710f9dd9 (10.42.42.38) 1.61ms
[I 200819 12:22:02 web:2250] 302 GET /generate_204_6a1d300c-f288-477c-9a47-443676fd45cd (10.42.42.38) 0.41ms
[I 200819 12:22:08 web:2250] 302 GET /generate_204_350c8620-d4fa-4fd3-a960-92a89bdc93f6 (10.42.42.38) 1.65ms

GET /gw.json?a=s.gw.token.get&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":46,"source":"ap","path":"broadcast"}}&t=18&v=3.0&sign=75ad6cb91673b884e2e9c6f8d094736e
Host: a3.tuyaus.com
User-Agent: ESP8266SDK
Connection: keep-alive

Answer s.gw.token.get
reply {"t":1597839747,"e":false,"success":true,"result":{"gwApiUrl":"http://10.42.42.1/gw.json","stdTimeZone":"-05:00","mqttRanges":"","timeZone":"-05:00","httpsPSKUrl":"https://10.42.42.1/gw.json","mediaMqttUrl":"10.42.42.1","gwMqttUrl":"10.42.42.1","dstIntervals":[],"mqttsUrl":"10.42.42.1","mqttsPSKUrl":"10.42.42.1","mediaMqttsUrl":"10.42.42.1","aispeech":"10.42.42.1"}}
[I 200819 12:22:27 web:2250] 200 GET /gw.json?a=s.gw.token.get&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":46,"source":"ap","path":"broadcast"}}&t=18&v=3.0&sign=75ad6cb91673b884e2e9c6f8d094736e (10.42.42.1) 20.11ms

POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000"}&t=19&v=3.0&sign=6a8082c29427a66158bc10ca98598110
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 485

payload 40DD6ADE8D7481782D5EC5EBBCBE4089CDA06990C12FBCFE39F6364ADF39D7ADAB683C9A21E5F5878B1E240BC933C1FFA829DCE8A955CD45A257FDCEAFE164A0E8427C9EEC654F2E8C162D37D70CEE7D8E0A5ADCEA9D9060B6C3E470488DE6B58859618360490C926AAA32E35B935BDE2AAF4AFB259F5CE7445821983872E8216D941EE7968B142B0A2B32D5A1B42B1C11BFB354572DA2974A00E8D9C2618CD0EFB73DE16C83F83B8EBE1F551986F42500FF45B75E9602209B666F648AE563D92843F85BAD1B7BC258B0D1220B32E6A0A3680BB8C52F762848355238E27BD08489DAD6B43E976E60EBAB08DD038EB317
Answer s.gw.dev.pk.active
reply {"t":1597839747,"e":false,"success":true,"result":{"schema":"[{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"}]","uid":"00000000000000000000","devEtag":"0000000000","secKey":"0000000000000000","schemaId":"0000000000","localKey":"0000000000000000"}}
TRIGGER UPGRADE IN 10 SECONDS
[I 200819 12:22:27 web:2250] 200 POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=08152440f4cfa201bf97&other={"token":"00000000"}&t=19&v=3.0&sign=6a8082c29427a66158bc10ca98598110 (10.42.42.1) 63.46ms

POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=08152440f4cfa201bf97&t=21&v=1.0&sign=11e385353b205f73688f8fa6597e8dbb
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 0

Answer tuya.device.dynamic.config.get
reply {"result":"fn8oBaEAaJe3I+enO7OkYdd0LkD9WHnY6k8vmvctrJZuwWxJ/HC6QUyG58ewMUHI9F2VBmqNqTqJcWuiX4YubGu8wmLVKJPf+QB1VYA8SYO7mevrGF2WUpAllBDW/Q5l","t":1597839749,"sign":"9b2f80aef0768480"}
[I 200819 12:22:29 web:2250] 200 POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=08152440f4cfa201bf97&t=21&v=1.0&sign=11e385353b205f73688f8fa6597e8dbb (10.42.42.1) 5.83ms

POST /gw.json?a=s.gw.update&et=1&gwId=08152440f4cfa201bf97&t=1597839750&v=2.0&sign=96be5199deb9ede5f78a12a50f172c08
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 229

payload {"gwId":"08152440f4cfa201bf97","verSw":"1.0.5","bv":"5.50","pv":"2.2","cdVer":"1.0.0","devAttribute":3}
Answer generic (s.gw.update)
reply {"result":"JqgC3KcL+PhFfrJ6QVst1lJlBfTA81IObkeu0CDyeb2FXmAf4muUZeCPnR1XSN8u","t":1597839751,"sign":"6750444535d7f880"}
[I 200819 12:22:31 web:2250] 200 POST /gw.json?a=s.gw.update&et=1&gwId=08152440f4cfa201bf97&t=1597839750&v=2.0&sign=96be5199deb9ede5f78a12a50f172c08 (10.42.42.1) 47.89ms

POST /gw.json?a=s.gw.dev.update&et=1&gwId=08152440f4cfa201bf97&t=1597839752&v=2.0&sign=aebe247a416bb3aa6add80bf86340866
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 197

payload {"devId":"08152440f4cfa201bf97","verSw":"1.0.5","cdVer":"1.0.0","devAttribute":3}
Answer generic (s.gw.dev.update)
reply {"result":"JqgC3KcL+PhFfrJ6QVst1oGHsWPdHgS+I6213ZrfE/mFXmAf4muUZeCPnR1XSN8u","t":1597839753,"sign":"4b04dfd48d61fc77"}
[I 200819 12:22:33 web:2250] 200 POST /gw.json?a=s.gw.dev.update&et=1&gwId=08152440f4cfa201bf97&t=1597839752&v=2.0&sign=aebe247a416bb3aa6add80bf86340866 (10.42.42.1) 51.78ms

POST /gw.json?a=atop.online.debug.log&et=1&gwId=08152440f4cfa201bf97&t=1597839753&sign=cc3aea8c99c2afe6a5d9b4168748fbb8
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 229

payload {"data":4,"exp":"epc1=0x00000000, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000"}
Answer atop.online.debug.log
reply {"result":"oQwdS0ZeSlfgX+dHrKUihnXqY9whLJxCs3bx8Uud4p+FXmAf4muUZeCPnR1XSN8u","t":1597839754,"sign":"55d48fcd5511ab35"}
[I 200819 12:22:34 web:2250] 200 POST /gw.json?a=atop.online.debug.log&et=1&gwId=08152440f4cfa201bf97&t=1597839753&sign=cc3aea8c99c2afe6a5d9b4168748fbb8 (10.42.42.1) 58.03ms
encoding {"data":{"gwId":"08152440f4cfa201bf97"},"protocol":15,"s":"1523715","t":"1597839757"} using protocol 2.2
b'2.2\xbb\xc6;\x8883975761\xb7\x98\xa7\x08\xc0\xc7\xa5\xc2JB\x9c_9\xed\x91m\xe7%\xf0E\xfa\x0b\xcc\x06\xd4kN_5#W\xb0\xfd\xe9y\xbb\x8a\xb0=\xc1\x89\x1b{\x8c\xe6\xb0?\x89\x91\xfa\xef\xd4\xa8\xffL\x1a\xef\x01\r\x8e\xbd\xf5EL\xab\x9a\xc2\xba0\xc5\xd7b\x84$L\xf4\xe3\xa08\xd6\xf0Pe\xa1\x9c=\xd0\xefw\xd2\x86i\xbd\xa8\xa4W'

POST /gw.json?a=tuya.device.upgrade.get&et=1&gwId=08152440f4cfa201bf97&t=1597839757&v=4.3&sign=ed31f32c4da22777f883f237bdc93c65
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 37

payload {"type":0}
Answer s.gw.upgrade.get
reply {"result":"NXBuln3ez+yclRKuHLyrIZFa9xM+0mFb9LQj7O2LTSrUE24kPlUfewWxjy66ka8i+if2gcvjrCBj3QU86Q1qxFgdNRT4xyl9Gf145roqTAsDwsiUfyt5tWfHXxi4+rNEblx1zwlRMvjzlvm8F22DqurYQfkNM4ZEPEbCV50oPT6z8fhl53+/foI98cWuvYhTuvuYxpQtpksOTUQHtwhh4Fh4F45WNdsPHzoa4J7L/wzRUDFvxAv1a7QVF95+HmBl0grAq/U4/3fvGixJkVPNYZMk5QV3H6P5gUMc3eruvOg=","t":1597839757,"sign":"8f847b9df3c0697a"}
[I 200819 12:22:37 web:2250] 200 POST /gw.json?a=tuya.device.upgrade.get&et=1&gwId=08152440f4cfa201bf97&t=1597839757&v=4.3&sign=ed31f32c4da22777f883f237bdc93c65 (10.42.42.1) 51.18ms

POST /gw.json?a=s.gw.upgrade.updatestatus&et=1&gwId=08152440f4cfa201bf97&t=1597839757&sign=4d73029292a48fa9b725fcadbb561abf
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 69

payload {"upgradeStatus":2}
Answer s.gw.upgrade.updatestatus
reply {"result":"JqgC3KcL+PhFfrJ6QVst1i1tN0Se7vmcFYoVtBCxVqeFXmAf4muUZeCPnR1XSN8u","t":1597839758,"sign":"cbee92d58888c26c"}
[I 200819 12:22:38 web:2250] 200 POST /gw.json?a=s.gw.upgrade.updatestatus&et=1&gwId=08152440f4cfa201bf97&t=1597839757&sign=4d73029292a48fa9b725fcadbb561abf (10.42.42.1) 68.96ms
[I 200819 12:22:45 web:2250] 206 HEAD /files/upgrade.bin (10.42.42.40) 17.26ms
[I 200819 12:22:49 web:2250] 200 GET /files/upgrade.bin (10.42.42.40) 4113.28ms
^CReceived SIGINT, exiting...


-----------

smarthack-wifi.log:

System info
===========
94acc3b
Linux my 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OpenSSL 1.1.1  11 Sep 2018
Dnsmasq version 2.79  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Python 3.6.9
===========
./setup_ap.sh: line 19: rfkill: command not found
Configuring AP interface...
RTNETLINK answers: File exists
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlx200db0394558...
Configuration file: /dev/stdin
Using interface wlx200db0394558 with hwaddr 20:0d:b0:39:45:58 and ssid "vtrust-flash"
wlx200db0394558: interface state UNINITIALIZED->ENABLED
wlx200db0394558: AP-ENABLED 
wlx200db0394558: AP-STA-CONNECTED f4:cf:a2:01:bf:97
wlx200db0394558: AP-STA-CONNECTED 04:4f:4c:39:72:1e
wlx200db0394558: AP-STA-DISCONNECTED f4:cf:a2:01:bf:97
wlx200db0394558: AP-STA-CONNECTED f4:cf:a2:01:bf:97
wlx200db0394558: AP-STA-DISCONNECTED f4:cf:a2:01:bf:97
wlx200db0394558: AP-STA-CONNECTED f4:cf:a2:01:bf:97
wlx200db0394558: interface state ENABLED->DISABLED
wlx200db0394558: AP-STA-DISCONNECTED f4:cf:a2:01:bf:97
wlx200db0394558: AP-STA-DISCONNECTED 04:4f:4c:39:72:1e
wlx200db0394558: AP-DISABLED 
nl80211: deinit ifname=wlx200db0394558 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
```

**Comment by kueblc** [comment]
Looks like your device is running the intermediate firmware. Restart the process but this time do not connect a phone, just plug the device in and press enter.

**Comment by membersound** [comment]
Thank you so much! That worked for both of my devices.
