### ISSUE TITLE
Smart Config fails on Gosund SP111: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC]

### ISSUE THREAD

**Issue by Pe-MaKer** [ct-Open-Source/tuya-convert#804]
I'm unable to flash the Gosund SP111 (Version 2500 Watt) device.

The AP starts up, smartphone connects, SP111 is set into discovery mode (blue light blinks fast).

As soon as I start the flashing routine, the blinking stops, and the scripts tries to "Resend the SmartConfig Packets" until it times out.

Please find here my logs:

**smarthack-psk.log**
```
new client on port 443 from 10.42.42.27:16557
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:48814
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:22643
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:39305
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:62224
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:23590
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:52637
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:36503
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:9530
ID: 02423f3f3f3f3f3f3f3f3f3f3f3f3f3f3f4cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
Prefix: b'B???????????????'
PSK: 1ba5826b9580b2c9bee1313c823a472a5afffc7725c94c2866017bd0f4b043b3
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:18564
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:18287
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:64759
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:16724
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:1363
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:18601
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:44869
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:24653
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:27214
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:17249
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:3004
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:28100
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:18425
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:8544
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:24596
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:8221
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:23001
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:9012
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:30844
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.27:10119
ID: 0242416f68626d643661473931494652314cc149fe6c7b373dacb48bc22278e3ddac47fa546639024d25a81a4c1f893174
PSK: f95ee0df92cd84cedce6c307d95bb7be81b523a91a84db72d4087277852944c4
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt
```

**smarthack-udp.log**
```
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^C
```

**smarthack-mqtt.log**
```
1603202361: mosquitto version 1.5.7 starting
1603202361: Using default config.
1603202361: Opening ipv4 listen socket on port 1883.
1603202361: Opening ipv6 listen socket on port 1883.
^C1603202678: mosquitto version 1.5.7 terminating
1603202799: mosquitto version 1.5.7 starting
1603202799: Using default config.
1603202799: Opening ipv4 listen socket on port 1883.
1603202799: Opening ipv6 listen socket on port 1883.
^C1603203099: mosquitto version 1.5.7 terminating
1603203343: mosquitto version 1.5.7 starting
1603203343: Using default config.
1603203343: Opening ipv4 listen socket on port 1883.
1603203343: Opening ipv6 listen socket on port 1883.
^C1603205524: mosquitto version 1.5.7 terminating
1603205537: mosquitto version 1.5.7 starting
1603205537: Using default config.
1603205537: Opening ipv4 listen socket on port 1883.
1603205537: Opening ipv6 listen socket on port 1883.
^C1603207395: mosquitto version 1.5.7 terminating
1603207526: mosquitto version 1.5.7 starting
1603207526: Using default config.
1603207526: Opening ipv4 listen socket on port 1883.
1603207526: Opening ipv6 listen socket on port 1883.
^C1603207622: mosquitto version 1.5.7 terminating
1603207655: mosquitto version 1.5.7 starting
1603207655: Using default config.
1603207655: Opening ipv4 listen socket on port 1883.
1603207655: Opening ipv6 listen socket on port 1883.
^C1603208192: mosquitto version 1.5.7 terminating
1603208218: mosquitto version 1.5.7 starting
1603208218: Using default config.
1603208218: Opening ipv4 listen socket on port 1883.
1603208218: Opening ipv6 listen socket on port 1883.
^C1603213656: mosquitto version 1.5.7 terminating
1603213849: mosquitto version 1.5.7 starting
1603213849: Using default config.
1603213849: Opening ipv4 listen socket on port 1883.
1603213849: Opening ipv6 listen socket on port 1883.
^C1603214194: mosquitto version 1.5.7 terminating
1603214267: mosquitto version 1.5.7 starting
1603214267: Using default config.
1603214267: Opening ipv4 listen socket on port 1883.
1603214267: Opening ipv6 listen socket on port 1883.
^C1603214432: mosquitto version 1.5.7 terminating
1603216215: mosquitto version 1.5.7 starting
1603216215: Using default config.
1603216215: Opening ipv4 listen socket on port 1883.
1603216215: Opening ipv6 listen socket on port 1883.
^C1603216342: mosquitto version 1.5.7 terminating
1603216373: mosquitto version 1.5.7 starting
1603216373: Using default config.
1603216373: Opening ipv4 listen socket on port 1883.
1603216373: Opening ipv6 listen socket on port 1883.
^C1603216508: mosquitto version 1.5.7 terminating
1603216640: mosquitto version 1.5.7 starting
1603216640: Using default config.
1603216640: Opening ipv4 listen socket on port 1883.
1603216640: Opening ipv6 listen socket on port 1883.
^C1603216798: mosquitto version 1.5.7 terminating
```

**smarthack-web.log**
```
Listening on 10.42.42.1:80
[32m[I 201020 18:57:50 web:2250][m 200 GET / (10.42.42.35) 5.29ms
^CReceived SIGINT, exiting...
```

**smarthack-wifi.log**
```
System info
===========
94acc3b
Linux octopi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
OpenSSL 1.1.1d  10 Sep 2019
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Python 3.7.3
===========
Configuring AP interface...
RTNETLINK answers: File exists
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlan0...
Configuration file: /dev/stdin
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:39:59:5f and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: AP-STA-CONNECTED 50:02:91:10:10:6f
wlan0: AP-STA-DISCONNECTED 50:02:91:10:10:6f
wlan0: AP-STA-CONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-STA-DISCONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-STA-CONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-STA-DISCONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-STA-CONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-STA-DISCONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-STA-CONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-STA-CONNECTED 50:02:91:10:10:6f
wlan0: interface state ENABLED->DISABLED
wlan0: AP-STA-DISCONNECTED 50:02:91:10:10:6f
wlan0: AP-STA-DISCONNECTED 6c:c7:ec:7b:ee:54
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
```

**Comment by kueblc** [comment]
Duplicate #483, unsupported firmware
