### ISSUE TITLE
My device's firmware is too new

### ISSUE THREAD

**Issue by xyzqazwsx** [ct-Open-Source/tuya-convert#925]
**Are you reporting a successful flash?**
No, I was unable to flash my device

**Do you have a question about configuring your newly flashed device?**
No

**Did you have issues getting a device to flash?**

I couldn't flash my device. It's **Tuya Fuers**, model **WIFID01**.
I built the latest tuya-convert software from github. I used a Raspberry Pi 4 as a host.

Console logs:
```
pi@raspberrypi:~/tuya-convert $ ./start_flash.sh 
tuya-convert v2.4.5
Checking for network interface wlan0... Found.
Checking UDP port 53... Available.
Checking UDP port 67... Available.
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking UDP port 6666... Available.
Checking UDP port 6667... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
======================================================
  Starting AP in a screen....
  Starting web server in a screen
  Starting Mosquitto in a screen
  Starting PSK frontend in a screen
  Starting Tuya Discovery in a screen

======================================================

IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue


======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
.Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
............
Timed out while waiting for the device to (re)connect
======================================================
Attempting to diagnose the issue...
Your device's firmware is too new.
Tuya patched the PSK vulnerability that we use to establish a connection.
You might still be able to flash this device over serial.
For more information and to follow progress on solving this issue see:
https://github.com/ct-Open-Source/tuya-convert/wiki/Collaboration-document-for-PSK-Identity-02
======================================================
Do you want to try flashing another device? [y/N] n
======================================================
Cleaning up...
Closing AP
Exiting...
pi@raspberrypi:~/tuya-convert $ 
```

smarthack-psk.log
```
new client on port 443 from 10.42.42.33:41242
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.33:41250
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.33:41252
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.22:59043
ID: 026745672b2a5980ca2b05fe8ede6152969189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'gEg+*Y\x80\xca+\x05\xfe\x8e\xdeaR\x96'
PSK: df1287a3ce8dd485aa52ae62b30d1bf2767a226a1c4dae331217b6f7aefd7200
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59044
ID: 0225b654703f5c0c952738d588c035f3189189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b"%\xb6Tp?\\\x0c\x95'8\xd5\x88\xc05\xf3\x18"
PSK: 07c1f8f207d17c4b558b69559e3559c125f75bd6e463327614ce8649d0b6e881
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.33:41256
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.22:59045
ID: 021fc1fc6081d4c7dd6248ca38913ecbfe9189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'\x1f\xc1\xfc`\x81\xd4\xc7\xddbH\xca8\x91>\xcb\xfe'
PSK: 332a7434545008efb0c1f40e155e004afe52583b8463b6e333a7364c29fae203
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59046
ID: 02a64f4fa6bf9773af2c2dfad09c97b30a9189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'\xa6OO\xa6\xbf\x97s\xaf,-\xfa\xd0\x9c\x97\xb3\n'
PSK: 63d2c90abcd7919e0685af74d821c3300811f00cb57e45f7088ac585c549f6bc
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59047
ID: 0224126a92ff2f7e88e73f697fd927674b9189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b"$\x12j\x92\xff/~\x88\xe7?i\x7f\xd9'gK"
PSK: f4651b73330a0fa8c15b99b0e39e03eb22daaccefd31a7ce883e577fc0a8ac6b
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59048
ID: 02dd425dd93e9ac317c6f5c32faf5e45d79189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'\xddB]\xd9>\x9a\xc3\x17\xc6\xf5\xc3/\xaf^E\xd7'
PSK: 351ad4befc9b8261971095b11c4f125115ca83fa8682a20c5f9702d9c7f5ab3b
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59049
ID: 02b05de5542d0648fc8da31c47b1f7118d9189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'\xb0]\xe5T-\x06H\xfc\x8d\xa3\x1cG\xb1\xf7\x11\x8d'
PSK: 87a61dcffe999e72b7ddc1b06eb1a8dcca47e38423fd664a3eeceae979b67ffd
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59050
ID: 02d5e931c3f396ff86543daf6e62b8b2d49189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'\xd5\xe91\xc3\xf3\x96\xff\x86T=\xafnb\xb8\xb2\xd4'
PSK: 59a1b7e32f9d8f7632047cabb6eed10df087213668f89a483867b693e4ba1971
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59051
ID: 029d329f88ee1f857742169f43ef32f15e9189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'\x9d2\x9f\x88\xee\x1f\x85wB\x16\x9fC\xef2\xf1^'
PSK: 6914cd04a048ae5aadb9d6bca07f83323a649c40f27d5928470c0f94b3430cfc
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.22:59052
ID: 02340b7b6b70e8e4c0539eb725f7813ee39189b512ce8c50d6e1e14915e8638842a35ff33126ac7389042d6f4c18799475
Prefix: b'4\x0b{kp\xe8\xe4\xc0S\x9e\xb7%\xf7\x81>\xe3'
PSK: 43d681159626f4a30a6375bff6c81e2ea4185c7be5cce8147c6117cb4ebaf6c6
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.33:41260
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.33:41262
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.33:41264
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.33:41266
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.33:41268
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.33:41274
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt
```

smarthack-mqtt.log
```
1615540602: mosquitto version 1.5.7 starting
1615540602: Using default config.
1615540602: Opening ipv4 listen socket on port 1883.
1615540602: Opening ipv6 listen socket on port 1883.
^C1615540705: mosquitto version 1.5.7 terminating
```

smarthack-udp.log
```
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
10.42.42.22 {"ip":"10.42.42.22","gwId":"bf5115ca1ecd704ba6trs9","active":0,"ablilty":0,"encrypt":true,"productKey":"key8ky3d8eshuygm","version":"3.3"}
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
^C
```

smarthack-web.log
```
Listening on 10.42.42.1:80
^CReceived SIGINT, exiting...
```

smarthack-wifi.log
```
System info
===========
61ba060
Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
OpenSSL 1.1.1d  10 Sep 2019
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.8-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Python 3.7.3
===========
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlan0...
Configuration file: /dev/stdin
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr 5a:13:1b:b0:33:33 and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
wlan0: AP-STA-CONNECTED aa:f6:42:66:67:9f
wlan0: AP-STA-CONNECTED 70:89:76:84:2f:3f
wlan0: interface state ENABLED->DISABLED
wlan0: AP-STA-DISCONNECTED 70:89:76:84:2f:3f
wlan0: AP-STA-DISCONNECTED aa:f6:42:66:67:9f
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...
```

My device looks like this
![image](https://user-images.githubusercontent.com/78627942/110919745-e341df00-831c-11eb-8ab0-552cdf43ebce.png)

**Comment by kueblc** [comment]
Hi @xyzqazwsx 

It seems like you answered your own question. There's nothing we can do if your firmware is too new. According to your udp log, it also looks like this is not an ESP based device, so there is no way to run ESP alternative firmware like Tasmota.
