### ISSUE TITLE
GoSund Smart Plug not flashing (3 of 4 devices)

### ISSUE THREAD

**Issue by erikm30** [ct-Open-Source/tuya-convert#937]
I got some Gosund Smart Plugs from Ama**n recently, and managed to flash only one of them without opening.

However, as opposed to other people here, this is what I get in

==> scripts/smarthack-psk.log <==
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt

Obviously I am not doing any Keyboard interrupts .. this seems to come from the Timeout.

The board of the device I opened was showing version 2.4 - I managed to flash this through serial, but would of course be nicer to do it over the air.
Any experience how to get this done ?

**Comment by kueblc** [comment]
Hi @erikm30 

What was the diagnosis? Logs?

Regarding

> KeyboardInterrupt
> 
> Obviously I am not doing any Keyboard interrupts ..

The script terminates by sending `^C` to subprocesses running in `screen`s
