### ISSUE TITLE
Ubuntu Errno: 1 permission denied

### ISSUE THREAD

**Issue by limitlesskeil** [ct-Open-Source/tuya-convert#946]
Alright people i have dug into this one as far as i can so looking for some help. attached are my logs and the error i have gotten.

I'm running Ubuntu 20.10 on Intel NUC utilizing a linksys wusb6300. i'm able to connect to vtrust wifi on my phone but as soon as i hit enter i get this error and i can't tell what it thinks it doens't have permission for. 

Any support would be appreciated. 

Traceback (most recent call last):
  File "./smartconfig/main.py", line 26, in <module>
    smartconfig( passwd, ssid, region, token, secret )
  File "/home/plex/tuya-convert/scripts/smartconfig/smartconfig.py", line 54, in smartconfig
    sock.send_multicast(multicast_head)
  File "/home/plex/tuya-convert/scripts/smartconfig/smartconfig.py", line 39, in send_multicast
    self._socket.sendto( b'\0', (ip, 30012))
PermissionError: [Errno 1] Operation not permitted

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/6443972/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/6443973/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/6443974/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/6443975/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/6443976/smarthack-wifi.log)

**Comment by emsilva** [comment]
Did you manage to find a solution? I'm running into the same error. Thanks mate.
