### ISSUE TITLE
Device Stopped Working after 2 days use

### ISSUE THREAD

**Issue by asosnovsky** [ct-Open-Source/tuya-convert#957]
Device:  Prime Smart Outlet Outdoor Plug CCWFIO232PK

For some reason after 2 days of working just fine, it start started blinking red and is no longer on my wifi network. I tried re-running tuya-convert, and it seemed to have picked it up, but failed to re-flash.

```bash
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..............................
Timed out while waiting for the device to (re)connect
Stopping smart config
======================================================
Attempting to diagnose the issue...
An ESP82xx based device connected according to your wifi log.
If this is the device you are trying to flash, another issue may be preventing it from flashing.
Otherwise, it could be that the device does not use an ESP82xx or it did not connect.
For additional information, check the *.log files inside the scripts folder.
Please include these logs when opening a new issue on our GitHub issue tracker.
======================================================
Do you want to try flashing another device? [y/N] n
======================================================
Cleaning up...
Closing AP
Exiting...
```

Logs 
```log
1624048394: New connection from 10.42.42.24 on port 1883.
1624048394: Client 44860572840d8e430b9b already connected, closing old connection.
1624048394: New client connected from 10.42.42.24 as 44860572840d8e430b9b (p1, c1, k60, u'44860572840d8e430b9b').
1624048394: Will message specified (107 bytes) (r0, q1).
1624048394:     tuya/smart/will
1624048394: Sending CONNACK to 44860572840d8e430b9b (0, 0)
1624048394: Received SUBSCRIBE from 44860572840d8e430b9b
1624048394:     smart/device/in/44860572840d8e430b9b (QoS 0)
1624048394: 44860572840d8e430b9b 0 smart/device/in/44860572840d8e430b9b
1624048394: Sending SUBACK to 44860572840d8e430b9b
1624048401: Received PUBLISH from 44860572840d8e430b9b (d0, q1, r0, m2, 'smart/device/out/44860572840d8e430b9b', ... (147 bytes))
1624048401: Sending PUBACK to 44860572840d8e430b9b (m2, rc0)
1624048406: Received PUBLISH from 44860572840d8e430b9b (d0, q1, r0, m3, 'smart/device/out/44860572840d8e430b9b', ... (147 bytes))
1624048406: Sending PUBACK to 44860572840d8e430b9b (m3, rc0)
1624048431: Received PUBLISH from 44860572840d8e430b9b (d0, q0, r0, m0, 'smart/device/out/44860572840d8e430b9b', ... (80 bytes))
1624048431: Received PUBLISH from 44860572840d8e430b9b (d0, q0, r0, m0, 'smart/device/out/44860572840d8e430b9b', ... (81 bytes))
1624048432: Received PUBLISH from 44860572840d8e430b9b (d0, q0, r0, m0, 'smart/device/out/44860572840d8e430b9b', ... (81 bytes))
1624048522: Client 44860572840d8e430b9b has exceeded timeout, disconnecting.
[  114.610019]~DLT~ 6985~INFO     ~FIFO /tmp/dlt cannot be opened. Retrying later...
1624285155: mosquitto version 1.6.9 starting
1624285155: Using default config.
1624285155: Opening ipv4 listen socket on port 1883.
1624285155: Opening ipv6 listen socket on port 1883.
^C1624285316: mosquitto version 1.6.9 terminating
[  285.431861]~DLT~ 6985~WARNING  ~Lost log messages in user buffer when exiting: 9
new client on port 443 from 10.42.42.21:60564
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:60566
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:60567
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:60568
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:60569
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:60570
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:60571
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:60572
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52919
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52920
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52921
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52922
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52923
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52925
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52924
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52926
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52927
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52928
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52929
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52930
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52931
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52932
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52933
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52934
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52935
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52936
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52940
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52942
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52943
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52944
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52945
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52946
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52947
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52948
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52950
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52952
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:52954
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56144
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56145
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56146
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56147
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56149
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56150
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56151
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56152
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56154
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:58632
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56155
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56156
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56157
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56158
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56159
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56160
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56161
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56162
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56163
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56165
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56166
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56167
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56168
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56169
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56170
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56171
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56172
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56173
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56174
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56176
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56178
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56180
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56181
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56182
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56183
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56185
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56187
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56188
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56189
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:56190
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61782
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61783
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61784
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61786
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61787
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61788
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61789
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61791
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61793
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61795
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61797
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:61799
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt
new client on port 443 from 10.42.42.21:59412
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59413
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59414
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59415
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59416
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59417
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59418
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59419
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59420
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59421
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59422
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59423
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59424
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59425
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59426
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59427
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59428
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59429
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59430
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59431
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59432
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:59436
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:49363
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:49364
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:49365
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:49366
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:49367
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:49368
could not establish sslpsk socket: [SSL: WRONG_SSL_VERSION] wrong ssl version (_ssl.c:1123)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.21:49370
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1123)
don't panic this is probably just your phone!
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt
^CListening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
^C
POST /gw.json?a=atop.online.debug.log&gwId=44860572840d8e430b9b&t=5&sign=e89ce4768f3eb34f0f8faf33a4b3f172
Host: 10.42.42.1
Ty-Ua: HW
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 229

payload {"data":4,"exp":"epc1=0x00000000, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000"}
Answer atop.online.debug.log
reply {"t":1624048396,"e":false,"success":true,"result":true}
[I 210618 16:33:16 web:2239] 200 POST /gw.json?a=atop.online.debug.log&gwId=44860572840d8e430b9b&t=5&sign=e89ce4768f3eb34f0f8faf33a4b3f172 (10.42.42.24) 4.69ms

POST /gw.json?a=tuya.device.dynamic.config.get&gwId=44860572840d8e430b9b&t=1624048396&v=1.0&sign=020eba920607cf2b9887d6f8a7520728
Host: 10.42.42.1
Ty-Ua: HW
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 0

Answer tuya.device.dynamic.config.get
reply {"t":1624048396,"e":false,"success":true,"result":{"validTime":1800,"time":1624048396,"config":{}}}
[I 210618 16:33:16 web:2239] 200 POST /gw.json?a=tuya.device.dynamic.config.get&gwId=44860572840d8e430b9b&t=1624048396&v=1.0&sign=020eba920607cf2b9887d6f8a7520728 (10.42.42.24) 1.44ms

POST /gw.json?a=tuya.device.upgrade.silent.get&gwId=44860572840d8e430b9b&t=1624048420&v=4.1&sign=a44c970e1e72fda125778130c896bb89
Host: 10.42.42.1
Ty-Ua: HW
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 37

payload {"subId":null}
Answer tuya.device.upgrade.get
reply {"t":1624048421,"e":false,"success":true,"result":{"auto":true,"type":0,"size":"505867","version":"9.0.0","url":"http://10.42.42.1/files/upgrade.bin","md5":"9aeeb1f7b6dacb6f251445aac49181a9"}}
[I 210618 16:33:41 web:2239] 200 POST /gw.json?a=tuya.device.upgrade.silent.get&gwId=44860572840d8e430b9b&t=1624048420&v=4.1&sign=a44c970e1e72fda125778130c896bb89 (10.42.42.24) 3.13ms

POST /gw.json?a=s.gw.upgrade.updatestatus&gwId=44860572840d8e430b9b&t=1624048421&sign=7f552611213e1fda1e262826066e0b26
Host: 10.42.42.1
Ty-Ua: HW
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 69

payload {"upgradeStatus":2}
Answer s.gw.upgrade.updatestatus
reply {"t":1624048421,"e":false,"success":true}
[I 210618 16:33:41 web:2239] 200 POST /gw.json?a=s.gw.upgrade.updatestatus&gwId=44860572840d8e430b9b&t=1624048421&sign=7f552611213e1fda1e262826066e0b26 (10.42.42.24) 2.46ms
[I 210618 16:33:51 web:2239] 206 GET /files/upgrade.bin (10.42.42.24) 5.19ms
[I 210618 16:33:52 web:2239] 206 GET /files/upgrade.bin (10.42.42.24) 1359.95ms
Listening on 10.42.42.1:80
^CReceived SIGINT, exiting...
wlp4s0: AP-STA-DISCONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-CONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-DISCONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-CONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-DISCONNECTED 36:b0:46:10:fc:6b
wlp4s0: AP-STA-CONNECTED 36:b0:46:10:fc:6b
wlp4s0: AP-STA-DISCONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-CONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-DISCONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-CONNECTED 84:0d:8e:43:0b:9b
wlp4s0: interface state ENABLED->DISABLED
wlp4s0: AP-STA-DISCONNECTED 84:0d:8e:43:0b:9b
wlp4s0: AP-STA-DISCONNECTED 36:b0:46:10:fc:6b
wlp4s0: AP-DISABLED 
wlp4s0: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlp4s0 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...
System info
===========
61ba060
Linux ari-ThinkPad-T460s 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
OpenSSL 1.1.1f  31 Mar 2020
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth nettlehash DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Python 3.8.5
===========
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlp4s0...
Configuration file: /dev/stdin
Using interface wlp4s0 with hwaddr f0:d5:bf:5f:53:e8 and ssid "vtrust-flash"
wlp4s0: interface state UNINITIALIZED->ENABLED
wlp4s0: AP-ENABLED 
wlp4s0: AP-STA-CONNECTED 36:b0:46:10:fc:6b
wlp4s0: interface state ENABLED->DISABLED
wlp4s0: AP-STA-DISCONNECTED 36:b0:46:10:fc:6b
wlp4s0: AP-DISABLED 
wlp4s0: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlp4s0 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...
```

**Comment by kueblc** [comment]
If you've flashed the device and it is no longer running stock firmware, tuya-convert would not be able to help you there.

Try asking in the support channels for your alternative firmware, Tasmota, Espurna, ESPHome, etc.

**Comment by asosnovsky** [comment]
Sorry I figured out the issue, I inputted two SSIDs for the network, and it was randomly switching between the two. I was able to fix this by going to the other vlan and updating the configs. Closing the ticket.
