### ISSUE TITLE
git clone sslpsk.git failed

### ISSUE THREAD

**Issue by nt7** [ct-Open-Source/tuya-convert#998]
Hi,

I am running this on a RPi4 with Raspbian,

when I run the install prereq script, I run into:
`Command "git clone -q https://github.com/drbild/sslpsk.git /tmp/pip-req-build-rwi4nyh7" failed with error code 1 in None`

manually issueing this command works fine, so not sure what the problem is.

If I run the start flash script, I get:

`======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..............
Timed out while waiting for the device to (re)connect
======================================================
Attempting to diagnose the issue...
An ESP82xx based device connected according to your wifi log.
If this is the device you are trying to flash, another issue may be preventing it from flashing.
Otherwise, it could be that the device does not use an ESP82xx or it did not connect.
For additional information, check the *.log files inside the scripts folder.
Please include these logs when opening a new issue on our GitHub issue tracker.
======================================================
Do you want to try flashing another device? [y/N] n`

The log files seem regular, with the exception of smarthack-psk.log

`'_ssl._SSLSocket' object has no attribute '_sslobj'
new client on port 443 from 10.42.42.39:421
'_ssl._SSLSocket' object has no attribute '_sslobj'
new client on port 443 from 10.42.42.39:49597
'_ssl._SSLSocket' object has no attribute '_sslobj'
new client on port 443 from 10.42.42.39:29827
'_ssl._SSLSocket' object has no attribute '_sslobj'
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt`

Although I'm only suspecting the last "KeyboardInterrupt" is caused by the script after trying 10 times to resend SmartConfig Packets.

Anywhere else I could look for more info?

**Comment by kueblc** [comment]
> `Command "git clone -q https://github.com/drbild/sslpsk.git /tmp/pip-req-build-rwi4nyh7" failed with error code 1 in None`
> 
> manually issueing this command works fine, so not sure what the problem is.

The command you shared here only downloads the dependency to a temporary folder, it does not install it. You may have run into a transient error while `pip` attempted to install the dependency. I would try running `install_prereq` again.
